load("discord")

discord.addCommand("add"::
    do(
        args.shift()
        def(num1 ;: int(args.(0)))
        def(num2 ;: int(args.(1)))
        msg.send( + (num1 ;: num2) )
    )
)

discord.addCommand("subtract"::
    do(
        args.shift()
        def(num1 ;: int(args.(0)))
        def(num2 ;: int(args.(1)))
        msg.send( - (num1 ;: num2) )
    )
)

discord.addCommand("multiply"::
    do(
        args.shift()
        def(num1 ;: int(args.(0)))
        def(num2 ;: int(args.(1)))
        msg.send( * (num1 ;: num2) )
    )
)

discord.addCommand("divide"::
    do(
        args.shift()
        def(num1 ;: int(args.(0)))
        def(num2 ;: int(args.(1)))
        msg.send( / (num1 ;: num2) )
    )
)

